"""
Export Service - Generate PDF and Markdown exports of analysis reports
"""

import structlog
import json
from typing import Dict, Any
from datetime import datetime

logger = structlog.get_logger(__name__)

class ExportService:
    
    def export_to_markdown(
        self,
        document_name: str,
        analysis_data: Dict[str, Any]
    ) -> str:
        """
        Export analysis to GitHub-flavored Markdown
        
        Args:
            document_name: Original document filename
            analysis_data: Dict with summary, risks, gaps, qa_report (JSON strings)
            
        Returns:
            Markdown formatted string
        """
        # Parse JSON strings
        summary = json.loads(analysis_data.get('structured_summary', '{}'))
        risks = json.loads(analysis_data.get('risk_assessment', '{}'))
        gaps = json.loads(analysis_data.get('gaps_and_questions', '{}'))
        qa_report = json.loads(analysis_data.get('qa_report', '{}'))
        
        overall_risk = analysis_data.get('overall_risk_level', 'Unknown')
        model_version = analysis_data.get('model_version', 'Unknown')
        created_at = analysis_data.get('created_at', datetime.now())
        
        # Build markdown
        md = f"""# Document Quality Analysis Report

**Document:** {document_name}  
**Analysis Date:** {created_at}  
**AI Model:** {model_version}  
**Overall Risk Level:** {overall_risk}

---

## 📋 Structured Summary

### Purpose
{summary.get('purpose', 'Not specified')}

### Scope

**In-Scope:**
{self._format_list(summary.get('scope_in', []))}

**Out-of-Scope:**
{self._format_list(summary.get('scope_out', []))}

### Key Features
{self._format_list(summary.get('key_features', []))}

### Constraints
{self._format_list(summary.get('constraints', []))}

### Assumptions
{self._format_list(summary.get('assumptions', []))}

### Stakeholders
{self._format_list(summary.get('stakeholders', []))}

---

## ⚠️ Risk Assessment

**Overall Risk Level:** {overall_risk}

### Identified Risks

{self._format_risks(risks.get('risks', []))}

---

## 🔍 Gaps & Questions

{self._format_gaps(gaps.get('gaps', []))}

---

## ✅ QA Report

### Feature Summary
{qa_report.get('feature_summary', 'Not available')}

### Recommended Test Types
{self._format_list(qa_report.get('recommended_test_types', []))}

### Test Ideas by Area

{self._format_test_ideas(qa_report.get('test_ideas', []))}

### High-Risk Scenarios
{self._format_numbered_list(qa_report.get('high_risk_scenarios', []))}

### Open Questions for Stakeholders
{self._format_numbered_list(qa_report.get('open_questions', []))}

---

*This report was generated by Amplified Document Quality Analyzer*
"""
        return md
    
    def _format_list(self, items: list) -> str:
        """Format list as markdown bullets"""
        if not items:
            return "- *None specified*"
        return "\n".join([f"- {item}" for item in items])
    
    def _format_numbered_list(self, items: list) -> str:
        """Format list as numbered markdown"""
        if not items:
            return "1. *None specified*"
        return "\n".join([f"{i+1}. {item}" for i, item in enumerate(items)])
    
    def _format_risks(self, risks: list) -> str:
        """Format risks as markdown sections"""
        if not risks:
            return "*No significant risks identified*"
        
        output = []
        for i, risk in enumerate(risks, 1):
            output.append(f"""#### {i}. {risk.get('title', 'Untitled Risk')}

**Category:** {risk.get('category', 'Unknown')}  
**Likelihood:** {risk.get('likelihood', 'Unknown')} | **Impact:** {risk.get('impact', 'Unknown')}

**Description:**  
{risk.get('description', 'No description')}

**Suggested Mitigation:**  
{risk.get('mitigation', 'No mitigation suggested')}

""")
        return "\n".join(output)
    
    def _format_gaps(self, gaps: list) -> str:
        """Format gaps as markdown sections"""
        if not gaps:
            return "*No significant gaps identified*"
        
        output = []
        for i, gap in enumerate(gaps, 1):
            questions = gap.get('questions', [])
            questions_md = "\n".join([f"   - {q}" for q in questions])
            
            output.append(f"""#### {i}. {gap.get('description', 'Untitled Gap')}

**Impact:** {gap.get('impact', 'Unknown')}

**Questions to Ask:**
{questions_md if questions else '   - *No questions provided*'}

""")
        return "\n".join(output)
    
    def _format_test_ideas(self, test_ideas: list) -> str:
        """Format test ideas by area"""
        if not test_ideas:
            return "*No test ideas generated*"
        
        output = []
        for idea in test_ideas:
            area = idea.get('area', 'General')
            test_cases = idea.get('test_cases', [])
            test_cases_md = "\n".join([f"   - {tc}" for tc in test_cases])
            
            output.append(f"""#### {area}

{test_cases_md if test_cases else '   - *No test cases*'}
""")
        return "\n".join(output)
    
    def export_to_pdf(
        self,
        document_name: str,
        analysis_data: Dict[str, Any]
    ) -> bytes:
        """
        Export analysis to PDF
        
        Note: This is a simplified implementation that converts Markdown to PDF.
        For production, consider using weasyprint or reportlab for better formatting.
        
        Args:
            document_name: Original document filename
            analysis_data: Dict with summary, risks, gaps, qa_report
            
        Returns:
            PDF bytes
        """
        # First, generate markdown
        markdown_content = self.export_to_markdown(document_name, analysis_data)
        
        try:
            # Try using markdown + weasyprint (if installed)
            import markdown
            from weasyprint import HTML, CSS
            from io import BytesIO
            
            # Convert markdown to HTML
            html_content = markdown.markdown(
                markdown_content,
                extensions=['tables', 'fenced_code', 'nl2br']
            )
            
            # Add basic CSS styling
            css_style = """
            <style>
                body {
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 40px auto;
                    padding: 20px;
                }
                h1 {
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }
                h2 {
                    color: #34495e;
                    margin-top: 30px;
                    border-bottom: 2px solid #ecf0f1;
                    padding-bottom: 5px;
                }
                h3, h4 {
                    color: #7f8c8d;
                }
                code {
                    background: #f4f4f4;
                    padding: 2px 6px;
                    border-radius: 3px;
                }
                table {
                    border-collapse: collapse;
                    width: 100%;
                    margin: 20px 0;
                }
                th, td {
                    border: 1px solid #ddd;
                    padding: 12px;
                    text-align: left;
                }
                th {
                    background-color: #3498db;
                    color: white;
                }
                strong {
                    color: #2c3e50;
                }
                hr {
                    border: none;
                    border-top: 2px solid #ecf0f1;
                    margin: 30px 0;
                }
            </style>
            """
            
            full_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>Document Quality Analysis - {document_name}</title>
                {css_style}
            </head>
            <body>
                {html_content}
            </body>
            </html>
            """
            
            # Generate PDF
            pdf_file = BytesIO()
            HTML(string=full_html).write_pdf(pdf_file)
            pdf_bytes = pdf_file.getvalue()
            
            logger.info(f"PDF generated successfully ({len(pdf_bytes)} bytes)")
            return pdf_bytes
            
        except ImportError:
            logger.warning("weasyprint not installed, falling back to markdown export")
            # Fallback: return markdown as text file (not ideal, but functional)
            # In production, you'd want to ensure weasyprint is installed
            raise NotImplementedError(
                "PDF export requires 'weasyprint' and 'markdown' packages. "
                "Install with: pip install weasyprint markdown"
            )
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise


# Global singleton
export_service = ExportService()
